service: auth-server2

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  timeout: 60 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthenURL:
    handler: handler.getAuthenURL
    events:
      - http:
          path: api/get-authen-url
          method: get
  getTokenAccess:
    handler: handler.getTokenAccess
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
      
